Update npm package @fragcolor/protos index.js to the latest version
fragcolor-xyz/protos pull request #4
Opened 2022-08-17 02:28 UTC by paulinechi

This npm package is used to get the proto rpc methods and types, so when there is a change in proto we don't need to manually update on the frontend.

2022-11-02 08:47 UTC, aang114 requested changes
LGTM

But I think I changed the polkadot.js version in package.json in Clamor. So we could keep that consistent? Thanks

2023-01-13 03:59 UTC, sinkingsugar commented
why not merged @aang114 ?

2023-01-16 10:18 UTC, aang114 commented
> why not merged @aang114 ?


> why not merged @aang114 ?

I just noticed this package literally just contains a single JavaScript object. I mistakingly thought it was using `@polkadot/api` as a dependency (that's why I asked Pauline to check the dependency version). 

Merging now

2023-01-16 10:32 UTC, aang114 approved these changes

2023-01-16 10:32 UTC, merged