Allow the Serialization of `FragmentPerms`
fragcolor-xyz/protos pull request #5
Opened 2022-09-05 17:59 UTC by aang114

We use a serialised `FragmentPerms` in the runtime function `get_instances()` in this clamor PR: https://github.com/fragcolor-xyz/clamor/blob/04cfa97436cb51d2410d5b897adcbcf5e75032aa/pallets/fragments/src/lib.rs#L1594-L1641

2022-09-05 23:39 UTC, sinkingsugar requested changes

2022-09-05 23:39 UTC, sinkingsugar commented on Cargo.toml
> +#    "serde",
Not sure about this, anyway delete if not used. Run cargo test to check also.

2022-09-05 23:39 UTC, sinkingsugar commented on Cargo.toml
> +serde = { version = "1.0.136", features = ["derive"], default-features = false } # optional = true }
I think optional if fine for std no?

2023-01-13 03:58 UTC, sinkingsugar commented
what's this? why this is stalled? @aang114

2023-01-16 10:12 UTC, aang114 commented
> what's this? why this is stalled? @aang114

`get_instances()` works - so I'm not even sure what this was for...I'll just close this PR for now

2023-01-16 10:12 UTC, closed without merging